services:
  php:
    container_name: php
    image: waynerichen/php-nginx:8.1-buster
    ports:
        - 8088:80
    volumes:
        - ./html:/var/www/html
        - ./default:/etc/nginx/sites-available/default
    environment:
      - TZ=Asia/Taipei
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb:10.7.4
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: TRUE
      TZ: Asia/Taipei
    restart: always
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=mariadb